name: Publicar documentacion

on: push

permissions:
  contents: write

jobs:
  test:
    name: ğŸ§ª Test
    runs-on: ubuntu-latest
    steps:

      - name: ğŸ‘ Checkout
        uses: actions/checkout@v4
    
      - name: â‡ï¸ Configurar Credenciales de Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    
      - name: â‡ï¸ Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
    
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
    
      - name: â‡ï¸ Preparar Python MkDocs Material
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
    
      - name: ğŸ“¥ Instalar Dependencias
        run: pip install -r requirements.txt
    
      - name: ğŸ› ï¸ Build de la documentacion
        run: mkdocs build



  despliegue:
    name: ğŸš€ Publicar
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:

      - name: ğŸ‘ Checkout
        uses: actions/checkout@v4
    
      - name: â‡ï¸ Configurar Credenciales de Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    
      - name: â‡ï¸ Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
    
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
    
      - name: â‡ï¸ Preparar Python MkDocs Material
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
    
      - name: ğŸ“¥ Instalar Dependencias
        run: pip install -r requirements.txt
    
      - name: ğŸš€ Publicar documentacion
        run: mkdocs gh-deploy --force
